CREATE DATABASE PROJETOETEC;
USE PROJETOETEC;
CREATE TABLE TBL_ETEC (
ID_ETEC BIGINT PRIMARY KEY AUTO_INCREMENT,
ID_CODIGO INT ,
TX_NOME_ETEC VARCHAR (150) NOT NULL,
NR_CEP BIGINT NOT NULL,
TX_ENDERECO VARCHAR (100) NOT NULL,
TX_BAIRRO VARCHAR (80) NOT NULL,
TX_CIDADE VARCHAR (80) NOT NULL,
NR_ALTITUDE DOUBLE NULL,
NR_LONGITUDE DOUBLE NULL,
DT_CRIACAO DATETIME
);


drop table TBL_ETEC

delete from TBL_ETEC where ID_ETEC in (5)

select * from TBL_ETEC